function sideNetwork(){
    return [
        {
            text:'计算机网络体系',
            collapsed: false,
            items:[
                {
                    text:'计算机网络概述',
                    link:'/net/network/network.md'
                },
                {
                    text:'计算机网络体系结构于参考模型',
                    link:'/net/network/01-network-basic.md'
                }
            ]
        },
        {
            text:'物理层',
            collapsed: false,
            items:[
                {
                    text:'通信基础',
                    link:'/net/network/02-communication-basic.md'
                },
                {
                    text:'传输介质',
                    link:'/net/network/02-transmission-medium.md'
                },
                {
                    text:'物理层设备',
                    link:'/net/network/02-physical-device.md'
                }
            ]
        },
        {
            text:'数据链路层',
            collapsed: false,
            items:[
                {
                    text:'功能',
                    link:'/net/network/03-feature.md'
                },
                {
                    text:'组帧',
                    link:'/net/network/03-framing.md'
                },
                {
                    text:'差错控制',
                    link:'/net/network/03-error-control.md'
                },
                {
                    text:'流量控制与可靠传输机制',
                    link:'/net/network/03-flow-control-reliable-transport-mechanism.md'
                },
                {
                    text:'介质访问控制',
                    link:'/net/network/03-media-access-control.md'
                },
                {
                    text:'局域网',
                    link:'/net/network/03-local-area-network.md'
                },
                {
                    text:'广域网',
                    link:'/net/network/03-wide-area-network.md'
                },
                {
                    text:'数据链路层设备',
                    link:'/net/network/03-data-link-layer-device.md'
                }
            ]
        },
        {
            text:'网络层',
            collapsed: false,
            items:[
                {
                    text:'网络层功能',
                    link:'/net/network/04-network-layer-function.md'
                },
                {
                    text:'路由算法',
                    link:'/net/network/04-routing-algorithm.md'
                },
                {
                    text:'IPV4',
                    link:'/net/network/04-ipv4.md'
                },
                {
                    text:'IPV6',
                    link:'/net/network/04-ipv6.md'
                },
                {
                    text:'路由协议',
                    link:'/net/network/04-routing-protocol.md'
                },
                {
                    text:'IP组播',
                    link:'/net/network/04-ip-multicast.md'
                },
                {
                    text:'移动IP',
                    link:'/net/network/04-mobile-ip.md'
                },
                {
                    text:'网络层设备',
                    link:'/net/network/04-network-layer-device.md'
                }
            ]
        },
        {
            text:'传输层',
            collapsed: false,
            items:[
                {
                    text:'传输层提供的服务',
                    link:'/net/network/05-transport-service.md'
                },
                {
                    text:'UDP协议',
                    link:'/net/network/05-UDP.md'
                },
                {
                    text:'TCP协议',
                    link:'/net/network/05-TCP.md'
                }
            ]
        },
        {
            text:'应用层',
            collapsed: false,
            items:[
                {
                    text:'网络层应用模型',
                    link:'/net/network/06-network-layer-application-model.md'
                },
                {
                    text:'域名系统DNS',
                    link:'/net/network/06-dns.md'
                },
                {
                    text:'文件传输系统FTP',
                    link:'/net/network/06-ftp.md'
                },
                {
                    text:'电子邮件',
                    link:'/net/network/06-email.md'
                },
                {
                    text:'万维网WWW',
                    link:'/net/network/06-www.md'
                }
            ]
        },
    ]
}
export default sideNetwork