function sidePrinciples(){
    return [
        {
            text:'计算机系统概述',
            collapsed: false,
            items:[
                {
                    text:'计算机发展历程',
                    link:'/net/principles/principles.md'
                },
                {
                    text:'计算机系统层次结构',
                    link:'/net/principles/01-computer-system-hierarchy.md'
                },
                {
                    text:'计算机性能指标',
                    link:'/net/principles/01-computer-performance-index.md'
                }
            ]
        },
        {
            text:'数据的表示和运算',
            collapsed: false,
            items:[
                {
                    text:'数制与编码',
                    link:'/net/principles/02-number-system-coding.md'
                },
                {
                    text:'定点数的表示与运算',
                    link:'/net/principles/02-representation-operation-fixed-point-numbers.md'
                },
                {
                    text:'浮点数的表示与运算',
                    link:'/net/principles/02-floating-point-number-representation-operation.md'
                },
                {
                    text:'算数逻辑单元ALU',
                    link:'/net/principles/02-alu.md'
                }
            ]
        },
        {
            text:'存储系统',
            collapsed: false,
            items:[
                {
                    text:'存储器的层次结构',
                    link:'/net/principles/03-hierarchy-memory.md'
                },
                {
                    text:'存储器的层次化结构',
                    link:'/net/principles/03-hierarchical-structure-memory.md'
                },
                {
                    text:'半导体随机存储器',
                    link:'/net/principles/03-semiconductor-random-access-memory.md'
                },
                {
                    text:'主存储器与CPU的连接',
                    link:'/net/principles/03-the-connection-between-the-main-memory-theCPU.md'
                },
                {
                    text:'双端口RAM和多模块存储器',
                    link:'/net/principles/03-dual-port-RAM-multi-module-memory.md'
                },
                {
                    text:'高速缓冲存储器',
                    link:'/net/principles/03-cache.md'
                },
                {
                    text:'虚拟存储器',
                    link:'/net/principles/03-virtual-memory.md'
                }
            ]
        },
        {
            text:'指令系统',
            collapsed: false,
            items:[
                {
                    text:'指令格式',
                    link:'/net/principles/04-instruction-format.md'
                },
                {
                    text:'指令寻址方式',
                    link:'/net/principles/04-instruction-addressing-mode.md'
                },
                {
                    text:'CISC和RISC的基本概念',
                    link:'/net/principles/04-basic-concepts-CISC-RISC.md'
                }
            ]
        },
        {
            text:'总线',
            collapsed: false,
            items:[
                {
                    text:'总线概述',
                    link:'/net/principles/05-bus-overview.md'
                },
                {
                    text:'总线仲裁',
                    link:'/net/principles/05-bus-arbitration.md'
                },
                {
                    text:'总线操作和定时',
                    link:'/net/principles/05-bus-operation-and-timing.md'
                },
                {
                    text:'总线标准',
                    link:'/net/principles/05-bus-standard.md'
                }
            ]
        },
        {
            text:'输入输出系统',
            collapsed: false,
            items:[
                {
                    text:'I/O系统基本概念',
                    link:'/net/principles/06-basic-concepts-IO-systems.md'
                },
                {
                    text:'外部设备',
                    link:'/net/principles/06-external-device.md'
                },
                {
                    text:'I/O接口',
                    link:'/net/principles/06-IO-interface.md'
                },
                {
                    text:'I/O方式',
                    link:'/net/principles/06-IO-mode.md'
                }
            ]
        },
    ]

}
export default sidePrinciples
