
function sideStruct(){
    return [
        {
            text:'前言',
            collapsed: false,
            items:[
                {
                    text:'基础概念',
                    link:'/net/struct/struct.md'
                },
                {
                    text:'抽象数据类型',
                    link:'/net/struct/01-abstruct.md'
                },
                {
                    text:'算法与算法分析',
                    link:'/net/struct/01-analysis.md'
                }
            ]
        },
        {
            text:'线性表',
            collapsed: false,
            items:[
                {
                    text:'线性表的定义',
                    link:'/net/struct/02-list-definition.md'
                },
                {
                    text:'线性表的顺序表示',
                    link:'/net/struct/02-list-chained.md'
                },
                {
                    text:'线性表的链式表示',
                    link:'/net/struct/02-list-sequence.md'
                }
            ]
        },
        {
            text:'栈和队列',
            collapsed: false,
            items:[
                {
                    text:'栈',
                    link:'/net/struct/03-stack.md'
                },
                {
                    text:'队列',
                    link:'/net/struct/03-queue.md'
                },
                {
                    text:'栈和队列的应用',
                    link:'/net/struct/03-stack-queue-apply.md'
                },
                {
                    text:'特殊矩阵的压缩和存储',
                    link:'/net/struct/03-compression-storage-special-matrices.md'
                }
            ]
        },
        {
            text:'串，数组，广义表',
            collapsed: false,
            items:[
                {
                    text:'串，数组，广义表的定义',
                    link:'/net/struct/04-string-array-table.md'
                },
                {
                    text:'串，数组，广义表的实现',
                    link:'/net/struct/04-string-array-table-realize.md'
                }
            ]
        },
        {
            text:'树和二叉树',
            collapsed: false,
            items:[
                {
                    text:'树的基本概念',
                    link:'/net/struct/05-tree-basic.md'
                },
                {
                    text:'二叉树的概念',
                    link:'/net/struct/05-binary-trees-concept.md'
                },
                {
                    text:'二叉树的遍历和线索二叉树',
                    link:'/net/struct/05-binary-trees-traversal-clues.md'
                },
                {
                    text:'树，森林',
                    link:'/net/struct/05-tree-forest.md'
                },
                {
                    text:'树和二叉树的应用',
                    link:'/net/struct/05-tree-and-binaryTree-apply.md'
                }
            ]
        },
        {
            text:'图',
            collapsed: false,
            items:[
                {
                    text:'图的基本概念',
                    link:'/net/struct/06-graph.md'
                },
                {
                    text:'图的存储及基本操作',
                    link:'/net/struct/06-grahp-storage-opertations.md'
                },
                {
                    text:'图的遍历',
                    link:'/net/struct/06-graph-traversal.md'
                },
                {
                    text:'图的应用',
                    link:'/net/struct/06-graph-apply.md'
                }
            ]
        },
        {
            text:'查找',
            collapsed: false,
            items:[
                {
                    text:'查找的基本概念',
                    link:'/net/struct/07-search-basic.md'
                },
                {
                    text:'顺序查找和折半查找',
                    link:'/net/struct/07-sequential-search-half.md'
                },
                {
                    text:'B树和B+树',
                    link:'/net/struct/07-tree-tree+.md'
                },
                {
                    text:'散列表',
                    link:'/net/struct/07-hash.md'
                }
            ]
        },
        {
            text:'排序',
            collapsed: false,
            items:[
                {
                    text:'排序的基本概念',
                    link:'/net/struct/08-sort.md'
                },
                {
                    text:'插入排序',
                    link:'/net/struct/08-insert-sort.md'
                },
                {
                    text:'交换排序',
                    link:'/net/struct/08-exchange-sort.md'
                },
                {
                    text:'选择排序',
                    link:'/net/struct/08-select-sort.md'
                },
                {
                    text:'归并排序和基数排序',
                    link:'/net/struct/08-merge-radix.md'
                },
                {
                    text:'各种内部排序算法的比较及应用',
                    link:'/net/struct/08-sort-apply.md'
                },
                {
                    text:'外部排序',
                    link:'/net/struct/08-external-sort.md'
                }
            ]
        },
    ]
}


export default  sideStruct